language: csharp
solution: CursoOnline.sln
install:
  - nuget restore CursoOnline.sln
  - nuget install xunit.runners -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release CursoOnline.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./CursoOnline.Dominio.Test/bin/Release/CursoOnline.Dominio.Test.dll